addons:
  chrome: stable
language: node_js
script:
  - npm run lint
  - 'npm run build:prod'
deploy:
  provider: firebase
  skip_cleanup: true
  on:
    branch: master
  token:
    secure: >-
      3ahecTjPOShFjrZuE/qWZTf3Me/u8xJXi+JaRTU5k4D3blSlRwy4TBHhNNXOraZkHA6midBcWe09Fd4qgTqYEgCeaAPkm//ERwd/0WaEn4dr7UEsAeomYIoXOveg1PRV6dmGEa8/cowziOy/0occt1inMTqu+rV8Bel+Qv3s5UupyaFKnerK3d9c5ZrD40+Sb1MXroWSZhlF0wraerhbhmo71DHe6KNNeXMyy8BXdjI1wg9KHcqfQ13txEGMHYW1b9prjYxE0MDnPFAivV0VuQeO7Z0QflJB/mnfWX7/0ufz3kDoN2FeLKVnv4EhzYJZJh8JHq5kMrKXOZqWBdwyNb31v/m61pPX3PlHmbLlFJA1fWt1YyFTlDjCetCQACMfZk5KbngVPyN50NrGQlw4Lm1DhAcH33RP4Mm6OV5OM4E4bdPRL/D85vAjgqJzoK9/40ZVBBv5H7tw5zKg67boqoezEjgP3KMGdMGSPQZvgo1ASedPxZmRS/nM5TwR4aC6TRpydaYltEfh1uPajRQXVxgCVqhAzrYQw9vZVscNTMXbLRX8EjN4F3tHXu3EMcWEj6/wjeR/B3bmvVSr+jX9WLl+2wRS2fX5HiuVxabrSdZsQ1GhS5DxCx1/o9z5knH3L5tfT5+Pwbm6gwxERXgwW+vA9Kp2xDOMMKlq7E6lcNM=
notifications:
  email:
    on_failure: change
    on_success: change
